Add support for arm architecture in Dockerfile

diff --git a/docker/app/Dockerfile b/docker/app/Dockerfile
--- a/docker/app/Dockerfile
+++ b/docker/app/Dockerfile
@@ -53,6 +53,10 @@ RUN if [ "${TARGETARCH}" = "arm64" ]; then \
       curl -L -o shoutrrr.tar.gz "https://github.com/nicholas-fedor/shoutrrr/releases/download/v$SHOUTRRR_VERSION/shoutrrr_linux_arm64v8_${SHOUTRRR_VERSION}.tar.gz"; \
     elif [ "${TARGETARCH}" = "amd64" ]; then \
       curl -L -o shoutrrr.tar.gz "https://github.com/nicholas-fedor/shoutrrr/releases/download/v$SHOUTRRR_VERSION/shoutrrr_linux_amd64_${SHOUTRRR_VERSION}.tar.gz"; \
+    elif [ "${TARGETARCH}" = "arm" ]; then \
+      curl -L -o shoutrrr.tar.gz "https://github.com/nicholas-fedor/shoutrrr/releases/download/v$SHOUTRRR_VERSION/shoutrrr_linux_armhf_${SHOUTRRR_VERSION}.tar.gz"; \
+    else \
+      echo "Error: Unsupported TARGETARCH '${TARGETARCH}'" >&2 && exit 1; \
     fi
 RUN tar -xzf shoutrrr.tar.gz
 RUN chmod +x shoutrrr
